@startuml


' A P P '
class App {
}
App --- FunctionalAssessment
App -- Trainer

class FunctionalAssessment {
    functionalSystems : List<FunctionalSystem>
    previousResults : List<FunctionalAssessmentResult>
}
class FunctionalSystem {
    - name : String
    - primaryTest : Test
    - secondaryTests : List<Test>
}

class Test {
    - name : String
    - testId : String
    - description : String
    - media : String
    - possibleStates : List<Strings>
}
class FunctionalProfile {
    assessmentResults : List<FunctionalAssessmentResult>
    currentFunctionalStates : List<FunctionalSystemResult>

}

class FunctionalAssessmentResult {
    functionalAssessmentId : String
    date : LocalDateTime
    primaryTestResult : TestResult
    secondaryTestResults : List<TestResult>
}
class FunctionalSystemResult {
   - primaryTestResult : TestResult
   - secondaryTestResults : List<TestResults>
   - secondaryCompensationPatterns : List<String>
}
class TestResult {
    - name : String
    - testId : String
    - result : int
    - state : String
    - notes : String
}
FunctionalProfile -- FunctionalAssessmentResult
FunctionalAssessmentResult -- FunctionalSystemResult
FunctionalSystemResult --TestResult


class Trainer {
    - trainerInfo : TrainerInfo
    - clients : List<Clients>
}

class Client {
    - info : ClientInfo
    - functionalProfile : FunctionalProfile
    - programs : List<Program>
}

class ClientInfo {
    - name : String
    - phoneNumber : String
    - email : String
}

Trainer -- Client
Client - ClientInfo
FunctionalProfile - Client
Client -- Program
FunctionalAssessment -- FunctionalSystem
FunctionalSystem -- Test

' ----------------------------------- `

class Program {
    - workouts : List<Workout>
    - programFlow : ProgramFlow
}

class ProgramFlow {
"defines assigned days for workouts, rest days etc"
"essentially the schedule for the week"
}

Program - ProgramFlow

class Workout {
    - exercises : List<ExerciseId>
    - dateCreated : LocalDate
    - workoutFlow : WorkoutFlow
}

class WorkoutFlow {
"\\defines sets, reps, weights for each exercises"
"\\defines exerciseOrder, circuits, etc."
}
class Exercise {
    - name : String
    - description : String
    - media : String
    - functionalSystemStateId : String
    - level : int
    - progression : Exercise
    - regression : Exercise
}
Program -- Workout
Workout - WorkoutFlow
Workout -- Exercise

@enduml
